### ISSUE TITLE
Argument #2 ($user) must be of type Laravel\Socialite\Two\User

### ISSUE THREAD

**Issue by kgnfth** [DirectoryTree/Bartender#10]
I get the following error after redirected to /auth/tumblr/callback?oauth_token=**
I just followed the installation instructions on a blank laravel setup

`DirectoryTree\Bartender\UserProviderRepository::exists(): Argument #2 ($user) must be of type Laravel\Socialite\Two\User, SocialiteProviders\Manager\OAuth1\User given, called in /vendor/directorytree/bartender/src/UserProviderHandler.php on line 41`

**Comment by stevebauman** [comment]
Ah shoot you're right @kgnfth, let me update this. I'll consider this as a bug fix even though this would be a major breaking change otherwise.

**Comment by kgnfth** [comment]
Thank you for your work!

**Comment by stevebauman** [comment]
@kgnfth Thanks @kgnfth! ❤️ 

I've just released [v1.2.0](https://github.com/DirectoryTree/Bartender/releases/tag/v1.2.0) with a patch for this. Run `composer update` and you're all set! 👍

**Comment by kgnfth** [comment]
I get this now :( 

`SocialiteProviders\Manager\OAuth1\Server::getTokenCredentials(): Argument #1 ($temporaryCredentials) must be of type League\OAuth1\Client\Credentials\TemporaryCredentials, bool given, called in /var/www/inertiajs.caproverhub.com/vendor/socialiteproviders/manager/src/OAuth1/AbstractProvider.php on line 175`

**Comment by stevebauman** [comment]
That looks like it's something else unrelated to Bartender. I'm not sure what that could be unfortunately.
