### ISSUE TITLE
Laravel 10 - migrations created in a folder which causes an error running them 

### ISSUE THREAD

**Issue by ssmusoke** [DirectoryTree/Bartender#3]
Steps to reproduce

1. Create a new L10 project composer create-project laravel/laravel="10.*" myProject
2. Install the package `composer require directorytree/bartender`
3. Publish the service provider `php artisan vendor:publish --provider="DirectoryTree\Bartender\BartenderServiceProvider"
4. The migrations will be created in a folder 

<img width="550" alt="Screenshot 2024-04-04 at 19 31 10" src="https://github.com/DirectoryTree/Bartender/assets/689900/ff40f330-b473-46e2-94e0-980ad55d148e">

**Comment by stevebauman** [comment]
Fixed in [v1.0.1](https://github.com/DirectoryTree/Bartender/releases/tag/v1.0.1). Thanks for the report! 🙏
