### ISSUE TITLE
Driver not supported error while following the basic installation steps 

### ISSUE THREAD

**Issue by ssmusoke** [DirectoryTree/Bartender#4]
Repo - https://github.com/ssmusoke/microsoft

Error screen shot 
<img width="1477" alt="Screenshot 2024-04-04 at 19 52 12" src="https://github.com/DirectoryTree/Bartender/assets/689900/bd9f08ba-2fd5-43f4-a8fd-9e5d8feeb072">

.env file configuration 
`AZURE_CLIENT_ID=16d3a74a-xxxx-4114-0000-92c3026027b5
AZURE_CLIENT_SECRET="ABCDEF~kN8Xib7rSX5ImYb3-WHATEVERGOESHERE"
AZURE_TENANT_ID=d2846d5f-9999-4de6-0000-6dac927610be
AZURE_REDIRECT_URI="/auth/microsoft/callback"`

**Comment by stevebauman** [comment]
Hi @ssmusoke,

When are you getting this? Is this a global exception (occurring when you attempt to load any page), or does this occur when you perform a specific action?

**Comment by ssmusoke** [comment]
I changed the login page to have the link using the redirect route, so when I click the link it throws the error

**Comment by stevebauman** [comment]
I see the issue, the `EventServiceProvider` hasn't been updated as shown in the Socialite Provider docs:

https://github.com/ssmusoke/microsoft/blob/1c4fabe4e75d8d8d087ff9a389bf72d0612fd5be/app/Providers/EventServiceProvider.php#L17-L21

https://socialiteproviders.com/Microsoft/#installation-basic-usage

```php
protected $listen = [
    \SocialiteProviders\Manager\SocialiteWasCalled::class => [
        // ... other providers
        \SocialiteProviders\Microsoft\MicrosoftExtendSocialite::class.'@handle',
    ],
];
```

I'll update the Bartender docs to ensure it's clear to look at the Socialite Provider install instructions 👍

**Comment by stevebauman** [comment]
Ok I've added clarity to the installation steps! 👍
